version: '3.8'
services:
  poi-api:
    container_name: poi-api
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - db

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_USER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
      image: postgres:16.2
      container_name: db
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - 5432:5432
